activities/urls.py
from django.urls import path
from .views import (
        ClientsView,
        HistoryActivitiesView,
        GetTotalCallsView,
        ScheduleView,
        CallSchedulingRegisterView,
        CallPopUpView,
        PopulateView,
        SystemMetricsView,
        ChangePriceView,
        change_boolean,
        show_tag
)

app_name = 'activities'

urlpatterns = [
    path('clients/', ClientsView.as_view(), name="clients"),
    path('test-history/', HistoryActivitiesView.as_view(), name="test-history"),
    path('getdata/', GetTotalCallsView.as_view(), name="getdata"),
    path('schedule/', ScheduleView.as_view(), name="schedule"),
    path('schedule/button', change_boolean, name="change"),
    path('system_metrics/', SystemMetricsView.as_view(), name="system_metrics"),
    path('call_popup/', CallPopUpView.as_view(), name= "call_popup"),
    path('call_scheduling/', CallSchedulingRegisterView.as_view(), name="call_scheduling"),
    path('change_price/', ChangePriceView.as_view(), name="change_price"),
    path('populate-db/', PopulateView.as_view(), name="populate-db"),
    path('schedule/tag', show_tag, name="schedule_detail"),
]

from django.conf import settings

if(settings.DEBUG):
    urlpatterns += [
        path('populate_db/', PopulateView.as_view(), name="populate_db")
    ]

calls/urls.py
from django.urls import path
from .views import CallModalView

app_name='calls'

urlpatterns = [
    path('modal/', CallModalView.as_view(), name="modal"),
]

common/urls.py
from django.urls import path
from .views import (IndexView, 
                    ClientListView)

app_name = 'common'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('clients/', ClientListView.as_view(), name='clients'),
]

users/urls.py
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    ProfileView,
    SignupView,
    CollaboratorProfileView,
    CollaboratorListView,
)

from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password-reset/', PasswordResetView.as_view(
            template_name='users/password-reset.html',
            success_url=reverse_lazy('users:password-reset-done'),
            email_template_name='users/password-reset-email.html',
            html_email_template_name='users/email-clickcall.html',
            subject_template_name='users/password-reset-subject.txt',
            from_email='Suporte Clickcall <templatedmailtest@gmail.com>'
        ),
        name='password-reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(
            template_name='users/password-reset-done.html'
        ),
        name='password-reset-done'),

    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(
            template_name='users/password-reset-confirm.html',
            success_url=reverse_lazy('users:password-reset-complete'),
        ),
        name="password-reset-confirm"),

    path('reset/done/', PasswordResetCompleteView.as_view(
            template_name='users/password-reset-complete.html'
        ),
        name="password-reset-complete"),

    path('collaborator-profile/', CollaboratorProfileView.as_view(),
        name='collaborator-profile'),

    path('collaborator-list/', CollaboratorListView.as_view(), 
        name='collaborator-list'),
]

common/models.py
from django.db import models

# Create your models here.

common/views.py
from django.views import generic
from django.urls import reverse_lazy

from calls.models import Contact, Tag
from django.views.generic import ListView


class IndexView(generic.RedirectView):
    url = reverse_lazy('users:login')


class ClientListView(ListView):
    model = Contact
    template_name='client_list.html'
    queryset = Contact.objects.all()
    paginate_by=5
    
    def get_context_data(self, **kwargs):
        context = super(ClientListView, self).get_context_data(**kwargs)
        context.update({
            'need-to-update':'update'
        })
        return context
    
    def get_queryset(self):
        context_queryset = super(ClientListView, self).get_queryset()
        request = self.request
        if 'filter-by' in request.GET:
            filter_by = request.GET.get('filter-by')
            search = request.GET.get('search')
            if search == '':
                return context_queryset
            if filter_by == 'name':
                context_queryset = context_queryset.filter(name__icontains = search)
            elif filter_by == 'tag':
                tags_to_find = Tag.objects.all().filter(name__icontains = search)
                context_queryset = context_queryset.filter(tag__in = tags_to_find)
        return context_queryset

common/templates/app.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="row">
        <div class="navbar">
            <div class="row top-row">
                <!-- Navbar -->
                <div class="navbar-item navbar-item-logo">
                    <img class="navbar-brand navbar-brand-desktop" 
                        src={% static 'img/clickcall_logo_white.png' %}
                        alt="Brand"/>
            
                    <img class="navbar-brand navbar-brand-mobile" 
                        src={% static 'img/clickcall_icon_white.png' %}
                        alt="Brand Mobile"/>
                </div>
                <div class="call-items">
                    <img src="{% static 'img/call.png' %}" alt="call-icon" class="call-icon">
                    <input type="text" name="pNumber" class="pNumber">
                    <button class="call-btn">Ligar</button>
                </div>
                <a class="logout-btn" href={% url 'users:logout' %}>
                    <img src="{% static 'img/shut-down-icon.png' %}" alt="shut-down-icon">
                </a>
            </div>
            <div class="navbar-item">
                <img class="navbar-brand navbar-brand-desktop" 
                        src={% static 'img/clickcall_logo_white.png' %}
                        alt="Brand"/>
    
                <img class="navbar-brand navbar-brand-mobile" 
                        src={% static 'img/clickcall_icon_white.png' %}
                        alt="Brand Mobile"/>
            </div>
            <div id="activities" class="navbar-item navbar-item-active">
                Atividades
            </div>  
            <div id="activities-child" class="navbar-subitem-list">
                <div class="navbar-item-subitem
                {% if request.path == '/activities/metrics' %}
                navbar-item-active 
                {% endif %}">
                    <a href="{% url "activities:system_metrics" %}">
                        Métricas do Sistema
                    </a>
                </div>
                    
                <div class="navbar-item-subitem
                    {% if request.path == '/activities/ranking' %}
                    navbar-item-active 
                    {% endif %}">
                    Ranking dos Funcionários
                </div>
            </div>
            
            <div class="navbar-item
            {% if request.path == '/metas' %}
            navbar-item-active 
            {% endif %}">
                <a href="#">
                    Metas
                </a>
            </div>

            <div class="navbar-item
            {% if request.path == '/clients' %}
            navbar-item-active 
            {% endif %}">
                <a href="#">
                    Clientes 
                </a>
            </div>

            <div class="navbar-item
            {% if request.path == '/users/profile' %}
            navbar-item-active 
            {% endif %}">
                <a href="#">
                    Meu Perfil
                </a>
            </div>
                
            <div class="navbar-item
            {% if request.path == '/tutorials' %}
            navbar-item-active 
            {% endif %}">
            <a href="#">
                Treinamentos
            </a>
            </div>
        </div>
        
        <div class="column">   
            <div class="app-viewport">
                {% block app_content %}
                {% endblock %}
            </div>
        </div>
</div>
{% endblock %}
    

common/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href={% static 'css/base.css' %}>
        <link rel="stylesheet" href={% static 'css/toasty.min.css' %}>
        <link rel="stylesheet" href={% static 'css/navbar.css' %} media="all"/>
        <link rel="stylesheet" href={% static 'css/style.min.css' %} media="all"/>
        <link rel="stylesheet" href={% static 'css/callbar.css' %} media="all"/>

        {% block head %}
        {% endblock head %}

        {% block css %}
        {% endblock css %}

        {% block links %}
        {% endblock links %}

        <title>
            Click Call - 
            {% block title %}
            {% endblock title %}
        </title>
    </head>
    <body>
        {% block content %}
        {% endblock content %}
        <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        
        <script src={% static 'js/tag-widget.js' %}></script>

        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

common/templates/client_list.html
{% extends "app.html" %}

{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/client-list.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
{% endblock links %}

{% block title %}
    Lista de Clientes
{% endblock title %}

{% block app_content %}
    <div class="content">
        <div class="client-header">
            <div>
                <h2>Lista de clientes</h2>
                <i class="fas fa-plus-circle"></i>
            </div>
            <form class="fitrar-clientes" method="GET" name="filter-clients">
                {% csrf_token %}
                <select name="filter-by">
                    <option value="name">
                        Filtrar por nome
                    </option>
                    <option value="tag">
                        Filtrar por tag
                    </option>
                </select>
                <div class='button-holder'>
                    <input type='text' placeholder='Search...' class='search-text-input' name="search"/>
                    <button type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>
        </div>
        <table class="client-table" cellspacing="0">
            <tr class="header-row">
                <th>Tags</th>
                <th>Nome do contato</th>
                <th>Status</th>
                <th>Número</th>
                <th>Última atualização</th>
                <th>Email</th>
                <th class="right-table"></th>
            </tr>
            {% for client in object_list %}
                <tr class="data-row">
                    <td>
                        {% for tag in client.tag.all %}
                            {{tag.name}}
                        {% endfor %}
                    </td>
                    <td>
                        {{client.name}}
                    </td>
                    <td>
                        {% if client.status == 'INACTIVE' %}
                            <p class="client-inactive">Inativo</p>
                        {% else %}
                            <p class="client-active">Ativo</p>
                        {% endif %}
                    </td>
                    <td>
                        {{client.cellphone}}
                    </td>
                    <td>
                        {{client.last_update | date:"d/m/Y - H:i"}}h
                    </td>
                    <td>
                        {{client.email}}
                    </td>
                    <td class="right-table">
                        <img class="call-icons" src="{% static 'img/call.png' %}">
                    </td>
                </tr>
            {% empty %}
            {% endfor %}
        </table>

        {% if is_paginated %}
        <ul class="pagination">
        {% if page_obj.has_previous %}
            <li>
                <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
            </li>
        {% endif %}
            <li class="">
                <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
            </li>
        {% if page_obj.has_next %}
            <li>
                <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
            </li>
        {% endif %}
        </ul>
        {% else %}
            <h3>Your File Exam</h3>
            <p>File not yet available</p>
        {% endif %}

    </div>
{% endblock app_content %}

{% block scripts %}
{% endblock scripts %} 