activities/urls.py
from django.urls import path
from .views import (
        ClientsView,
        HistoryActivitiesView,
        GetTotalCallsView,
        ScheduleView,
        CallSchedulingRegisterView,
        CallPopUpView,
        PopulateView,
        SystemMetricsView,
        ChangePriceView,
        change_boolean,
        show_tag
)

app_name = 'activities'

urlpatterns = [
    path('clients/', ClientsView.as_view(), name="clients"),
    path('test-history/', HistoryActivitiesView.as_view(), name="test-history"),
    path('getdata/', GetTotalCallsView.as_view(), name="getdata"),
    path('schedule/', ScheduleView.as_view(), name="schedule"),
    path('schedule/button', change_boolean, name="change"),
    path('system_metrics/', SystemMetricsView.as_view(), name="system_metrics"),
    path('call_popup/', CallPopUpView.as_view(), name= "call_popup"),
    path('call_scheduling/', CallSchedulingRegisterView.as_view(), name="call_scheduling"),
    path('change_price/', ChangePriceView.as_view(), name="change_price"),
    path('populate-db/', PopulateView.as_view(), name="populate-db"),
    path('schedule/tag', show_tag, name="schedule_detail"),
]

from django.conf import settings

if(settings.DEBUG):
    urlpatterns += [
        path('populate_db/', PopulateView.as_view(), name="populate_db")
    ]

calls/urls.py
from django.urls import path
from .views import CallModalView

app_name='calls'

urlpatterns = [
    path('modal/', CallModalView.as_view(), name="modal"),
]

clients/urls.py
from django.urls import path
from .views import NewContactView

app_name='clients'

urlpatterns = [
    path('new_contact', NewContactView.as_view(), name='new_contact'),
]

activities/models.py
from django.db import models

# Create your models here.

calls/models.py
from __future__ import unicode_literals
from django.core.validators import RegexValidator
from django.db import models
import datetime


class Contact(models.Model):
    ACTIVE = 'AC'
    INACTIVE = 'IN'
    STATUS_CHOICES = (
        ('ACTIVE', 'Ativo'),
        ('INACTIVE', 'Inativo'),
    )

    # cellphone_regex = RegexValidator(
    #     regex=r'^\(\d{2}\)\d{1}-\d{4}-\d{4}$',
    #     message="O número deve ser cadastrado da seguinte forma:\
    #             (DD)9-9999-9999"
    # )

    # phone_regex = RegexValidator(
    #     regex=r'^\(\d{2}\)\d{4}-\d{4}$',
    #     message="O número deve ser cadastrado da seguinte forma:\
    #             (DD)9999-9999"
    # )

    # email_regex = RegexValidator(
    #     regex=r'^([\w\-]+\.)*[\w\- ]+@([\w\- ]+\.)+([\w\-]{2,3})$',
    #     message="O email deve ser cadastrado da seguinte forma:\
    #              email@email.com"
    # )

    name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name="Nome"
    )

    company_name = models.CharField(
        max_length=40,
        blank=False,
        verbose_name="Empresa"
    )

    email = models.EmailField(
        max_length=256,
        blank=False,
        verbose_name="Email"
    )

    cellphone = models.CharField(
        max_length=20,
        verbose_name="Celular",
    )

    phone = models.CharField(
        max_length=20,
        verbose_name="Telefone",
    )

    adress = models.CharField(
        max_length=256,
        verbose_name="Endereço"
    )

    last_update = models.DateTimeField(
        auto_now=False,
        default=datetime.datetime.now,
        verbose_name="Última atualização"
    )

    status = models.CharField(
        max_length=8,
        choices=STATUS_CHOICES,
        default=ACTIVE,
        verbose_name="Status"
    )

    tag = models.ManyToManyField(
        'Tag',
        verbose_name="Tag"
    )

    class Meta:
        verbose_name = "Contato"
        verbose_name_plural = "Contatos"

    def __str__(self):
        return self.name.capitalize()


class Tag(models.Model):
    name = models.CharField(
        max_length=50,
        primary_key=True,
        verbose_name="Nome"
    )

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return self.name.capitalize()


class Call (models.Model):
    RECEBIDA = 'RC'
    ATENDIDA = 'AT'
    NAO_ATENDIDA = 'NA'
    ABANDONADA = 'AB'
    OCUPADO = 'BU'
    EM_PROGRESSO = 'IN'
    PENDENTE = 'PN'
    STATUS_CHOICES = (
        ('RECEBIDA', 'Recebida'),
        ('ATENDIDA', 'Atendida'),
        ('NAO_ATENDIDA', 'Não Atendida'),
        ('ABANDONADA', 'Abandonada'),
        ('OCUPADO', 'Ocupado'),
        ('EM PROGRESSO', 'Em Progresso'),
        ('PENDENTE', 'Pendente'),
    )

    call_id = models.AutoField(
        primary_key=True,
        verbose_name="Número da Ligação",
    )

    # duration = models.TimeField(
    #     auto_now=False,
    #     verbose_name="Duração"
    # )

    call_24_hours = models.BooleanField(
        default=False,
        verbose_name="Chamada adiada"
    )

    email_sended = models.BooleanField(
        default=False,
        verbose_name="Email enviado"
    )

    paid = models.BooleanField(
        default=False,
        verbose_name="Pagamento efetuado"
    )

    contact = models.ForeignKey(
        'Contact',
        on_delete=models.CASCADE,
        verbose_name="Contato"
    )

    notes = models.TextField(
        max_length=256,
        verbose_name="Anotações"
    )

    subject = models.ManyToManyField(
        'Subject',
        verbose_name="Assunto",
        max_length=3
    )

    status = models.CharField(
        max_length = 12, 
        choices = STATUS_CHOICES, 
        default = RECEBIDA, 
        verbose_name = "Status"
    )
    value = models.DecimalField(
        # default=0,
        max_digits=8,
        decimal_places=2,
        verbose_name="Valor"
    )
    date_scheduling = models.DateTimeField(
        auto_now = False,
        verbose_name = "Data e Hora da ligação"
    )

    class Meta:
        verbose_name = "Chamada"
        verbose_name_plural = "Chamadas"

    def __str__(self):
        return self.contact.name.capitalize() + " " + datetime.datetime.strftime(
            self.contact.last_update, "%d/%m/%Y"
        )

class Subject(models.Model):
    name = models.CharField(
        max_length=256,
        primary_key=True,
        verbose_name="Nome"
    )

    class Meta:
        verbose_name = "Assunto"
        verbose_name_plural = "Assuntos"

    def __str__(self):
        return self.name.capitalize()

activities/forms.py
from django import forms
from django.forms import DateTimeField
from calls.models import Contact, Tag, Call


class ContactForm(forms.ModelForm):
    """
    Form that handles the contact creation
    """
    raw_tags = forms.CharField(widget=forms.HiddenInput())

    def save(self, commit=True):
        tags_name = self.cleaned_data.get('raw_tags').split(',') 
        # TODO: create the m2m relationship
        for tag_name in tags_name:
            if Tag.objects.filter(name=tag_name).exists():
                pass
            # create the relationship if the tag exists
            else:
                Tag.objects.create(
                    name=tag_name)
            # create the relationship if the tag doesn't exists

        return super().save()

    class Meta:
        model = Contact
        fields = '__all__'
        exclude = ['tag', 'last_update', 'status']

class CallSchedulingForm(forms.ModelForm):
    # date_scheduling = DateTimeField(input_formats=["%d %m %Y %H:%M"])
    class Meta:
        model = Call
        fields = ['date_scheduling']

class ChangePriceForm(forms.ModelForm):
    class Meta:
        model = Call
        fields = ['value']
       
class NotesForm(forms.ModelForm):
    class Meta:
        model = Call
        fields = ['notes']
        # fields = '__all__'

activities/views.py
import json as simplejson
from django.http import HttpResponse, JsonResponse
from datetime import datetime
import datetime
import pytz
from django.shortcuts import render
from django.views import generic


from django.views.generic import (
    DetailView,
    CreateView,
    TemplateView
)

from django.urls import reverse_lazy

from activities.objects import Year
from activities.factory import create

from calls.models import (
    Call,
    Contact,
    Tag,
)
from .forms import ContactForm, CallSchedulingForm, ChangePriceForm, NotesForm


class PopulateView(generic.View):
    """
    Populates de database
    """
    def get(self, request, *args, **kwargs):
        return create()


class SystemMetricsView(generic.TemplateView):
    """
    View to render the system metrics
    """
    template_name = "system-metrics.html"


class GetTotalCallsView(generic.View):
    """
    Returns info about the calls in JSON format
    """
    def get(self, request, *args, **kwargs):
        wish = request.GET.get('filterby')
        if(wish == 'yearly'):
            return HttpResponse(self.yearly())
        if(wish == 'monthly'):
            return HttpResponse(self.monthly())
        if(wish == 'daily'):
            return HttpResponse(self.daily())

    def yearly(self, *args, **kwargs):
        """
        Returns the calls grouped by year
        """
        json_response = []
        this_year = datetime.datetime.now().year
        for year in range(this_year, this_year-10, -1):
            year_object = {}
            this_year_calls = Call.objects.filter(date__year=year)
            number_of_calls = this_year_calls.count()
            year_object['year'] = year
            year_object['calls'] = number_of_calls
            year_object['received'] = this_year_calls.filter(status='RECEBIDA').count()
            year_object['answered'] = this_year_calls.filter(status='ATENDIDA').count()
            year_object['declined'] = this_year_calls.filter(status='ABANDONADA').count()
            year_object['not_answered'] = this_year_calls.filter(status='NAO_ATENDIDA').count()
            json_response.append(year_object)
        return simplejson.dumps(json_response)

    def monthly(self, *args, **kwargs):
        """
        Returns the calls grouped by month
        """
        json_response = []
        this_year = datetime.datetime.now().year
        this_month = datetime.datetime.now().month
        count = 0
        month = this_month
        year = this_year
        while(count != 13):
            month_object = {}
            if(month == 0):
                month = 12
                year -= 1
            elif(month >= 0):
                month_object['month'] = month
                month_object['year'] = year
                month_calls = Call.objects.filter(date__year=year, date__month=month)
                month_object['calls'] = month_calls.count()
                month_object['received'] = month_calls.filter(status='RECEBIDA').count()
                month_object['answered'] = month_calls.filter(status='ATENDIDA').count()
                month_object['declined'] = month_calls.filter(status='ABANDONADA').count()
                month_object['not_answered'] = month_calls.filter(status='NAO_ATENDIDA').count()
                json_response.append(month_object)
                month -= 1
            count += 1
        return simplejson.dumps(json_response)

    def daily(self, *args, **kwargs):
        """
        Returns the calls grouped by day
        """
        today = datetime.datetime.now()
        days_ago = today - datetime.timedelta(days=31)
        days_and_months = []
        end_loop_date = today + datetime.timedelta(days=1)

        while(days_ago.day != end_loop_date.day or
              days_ago.month != end_loop_date.month):

            days_and_months.append({
                'day': days_ago.day,
                'month': days_ago.month,
                'year': days_ago.year
            })
            days_ago = days_ago + datetime.timedelta(days=1)
        json_response = []

        for search_date in days_and_months:
            day_object={}
            day_object['date'] = search_date

            day_calls = Call.objects.filter(
                date__year=search_date['year'],
                date__month=search_date['month'],
                date__day=search_date['day']
            )

            day_object['calls'] = day_calls.count()
            day_object['received'] = day_calls.filter(status='RECEBIDA').count()
            day_object['answered'] = day_calls.filter(status='ATENDIDA').count()
            day_object['declined'] = day_calls.filter(status='ABANDONADA').count()
            day_object['not_answered'] = day_calls.filter(status='NAO_ATENDIDA').count()
            json_response.append(day_object)
        return simplejson.dumps(json_response)


class ScheduleView(generic.ListView):
    model = Call
    template_name = "call-history.html"
    context_object_name = 'calls'
    queryset = Call.objects.all()

    today = datetime.datetime.now()
    yesterday = today - datetime.timedelta(days=1)

    today_calls = Call.objects.filter(
            date_scheduling__date__year=today.year,
            date_scheduling__date__month=today.month,
            date_scheduling__date__day=today.day
    )

    yesterday_calls = Call.objects.filter(
            date_scheduling__date__year=yesterday.year,
            date_scheduling__date__month=yesterday.month,
            date_scheduling__date__day=yesterday.day
    )

    def get_context_data(self, **kwargs):  
        today = datetime.datetime.now()
        yesterday = today - datetime.timedelta(days=1)
        context = super(ScheduleView, self).get_context_data(**kwargs)
        context.update({
            'today': self.today,
            'today_calls': Call.objects.filter(
                                date_scheduling__date__year=today.year,
                                date_scheduling__date__month=today.month,
                                date_scheduling__date__day=today.day
                                ),
            'yesterday': self.yesterday,
            'yesterday_calls': Call.objects.filter(
                                date_scheduling__date__year=yesterday.year,
                                date_scheduling__date__month=yesterday.month,
                                date_scheduling__date__day=yesterday.day
                                )
        })
        return context

class HistoryActivitiesView(generic.ListView):
    """
    View to access the history of acitivities
    """
    template_name = "history-agenda.html"
    model = Call


class ClientsView(CreateView):
    """
    View to handles the clients
    """
    model = Contact
    template_name = 'clients.html'
    form_class = ContactForm
    success_url = reverse_lazy('activities:clients')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, *kwargs)
        context["tags"] = Tag.objects.all()
        return context

    def form_valid(self, form):
        form.save()
        raw_tags = form.cleaned_data['raw_tags'].split(',')

        for raw_tag in raw_tags:
            tag = Tag.objects.filter(name=raw_tag)
            form.instance.tag.add(tag.get(name=raw_tag))

        return super(ClientsView, self).form_valid(form)

    def form_invalid(self, form):
        return super(ClientsView, self).form_invalid(form)
        # import ipdb
        # ipdb.set_trace()

class CallSchedulingRegisterView(CreateView):
    model = Call
    template_name = 'call-scheduling.html'
    form_class = CallSchedulingForm
    success_url = reverse_lazy('activities:call_scheduling')

    def form_valid(self, form):
        from datetime import datetime, timezone
        call = Call.objects.get(pk = int (self.request.GET.get('pk')))
        date_scheduling = self.request.POST['date_scheduling']
        valid_datetime = datetime.strptime(date_scheduling, '%d/%m/%Y %H:%M')
        form = CallSchedulingForm(instance=call, data=self.request.POST)
        instance = form.save(commit=False)
        instance.date_scheduling = valid_datetime
        instance.save()
        return super(CallSchedulingRegisterView, self).form_valid(form)
        
    def form_invalid(self, form):
        # import ipdb
        # ipdb.set_trace()
        return super(CallSchedulingRegisterView, self).form_invalid(form)

class ChangePriceView(CreateView):
    model = Call
    template_name = 'change-price.html'
    form_class = ChangePriceForm
    success_url = reverse_lazy('activities:change_price')

    def form_valid(self, form):
        call = Call.objects.get(pk = int (self.request.GET.get('pk')))
        price = self.request.POST['value']
        form = ChangePriceForm(instance=call, data=self.request.POST)
        instance = form.save(commit=False)
        instance.value = price
        instance.save()
        return super(ChangePriceView, self).form_valid(form)
        
    def form_invalid(self, form):
        # import ipdb
        # ipdb.set_trace()
        return super(ChangePriceView, self).form_invalid(form)

class CallPopUpView(CreateView):
    model = Call
    template_name = 'call-popup.html'
    form_class = NotesForm
    success_url = reverse_lazy('activities:schedule')

    def form_valid(self, form):
        call = Call.objects.get(pk = int (self.request.GET.get('pk')))
        notes = self.request.POST['notes']
        form = NotesForm(instance=call, data=self.request.POST)
        # import ipdb
        # ipdb.set_trace()
        instance = form.save(commit=False)
        instance.notes = notes
        instance.save()
        return super(CallPopUpView, self).form_valid(form)
        
    def form_invalid(self, form):
        # import ipdb
        # ipdb.set_trace()
        return super(CallPopUpView, self).form_invalid(form)

    def get_context_data(self, **kwargs):

clients/views.py
from django.shortcuts import render
from django.views import generic


class NewContactView(generic.TemplateView):
    template_name='new_contact.html'

activities/templates/call-history-detail.html
{% load staticfiles %}

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Call History Detail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    

    {% block css %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/call-history-detail.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,700" rel="stylesheet">
    {% endblock %}

    {% block content %}
    <div class="container-detail" id="container-detail-a">
        <div class="information">
            <span class="company-name" get-data="data-company"></span>
            <span class="basic-information">Telefone: <span get-data="data-cellphone"></span></span>
            <span class="basic-information">Contato: <span get-data="data-name"></span></span>
            <span class="basic-information">Email: <span get-data="data-email"></span></span>
            <div class="calendar">
                <img src="{% static 'img/calendar.png' %}">
                <span get-data="data-date"></span>
            </div>
            <div class="money">
                <img src="{% static 'img/coin.png' %}">
                <span><span get-data="data-value"></span></span>
            </div>
        </div>
        <div class="information-buttons">
            <img src="{% static 'img/information-email.png' %}">
            <img src="{% static 'img/trash.png' %}">
            <img src="{% static 'img/waiting-call.png' %}">
            <img id="button_id" src="{% static 'img/call.png' %}">
             
        </div>
        <div class="notes">
            <span class="notes-title">Anotações:</span>
            <span class="notes-box">
              <span class="notes-text" get-data="data-notes"></span>
            </span>
        </div>
        <div class="tags">
            <span>Tags:</span>
            <div class="tag-row" id="tag-row">
            </div>
        </div>
    </div>
    <!-- <script src="main.js"></script> -->
    <script src="{% static 'js/show-detail.js' %}"></script>
    {% endblock %}

activities/templates/call-history.html
{% extends "app.html" %}
{% load staticfiles %}

{% block head %}
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Click Call - Call History</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/call-history.css' %}" />
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/fontello.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,700" rel="stylesheet">
{% endblock %}

{% block app_content %}
    <div class="extern">
      {% include "includes/history-table.html" %}
      {% include "includes/history-activities.html" %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/change-indicator.js' %}"></script>
    <script src="{% static 'js/show-detail.js' %}"></script>
    <script src="{% static 'js/call-history.js' %}"></script>
{% endblock %}

activities/templates/call-popup.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block links %}
<!-- <link rel="stylesheet" type="text/css" href = "{% static 'css/call-scheduling.css' %}"> -->
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/fontello.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,700" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="../../static/datetimepicker-2.5.20/jquery.datetimepicker.css"/ >
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/call-popup.css' %}">
{% endblock %}

{% block content %}
    <div class = "popup">
        <div class="new-call">
            <div class="call-contact">
                <img class="profile" src="{% static 'img/call-perfil.png' %}">
                <div class="title">
                    <span class="contact">{{call.contact.name|title}}</span>
                    <span class="company">{{call.contact.company_name|title}}</span>
                </div>
                <div class="call-number">
                    <span class="status">Ligando...</span>
                    <span class="number">{{call.contact.phone}}</span>
                </div>
                <div class="buttons">
                    <img src="{% static 'img/call-2.png' %}" class="call">
                    <img src="{% static 'img/aguardar.png' %}" class="wait">
                    <img src="{% static 'img/desligar.png' %}" class="off">
                </div>

            </div>
            <span class="divisor"></span>
            <div class="call-information">
                <div class="general-information">
                    <div class="box-informations">
                        <a class="date">
                            <img class="calendar" src="{% static 'img/calendar.png' %}">
                            <span class="description">{{call.date_scheduling|date:"d/m/Y"}}</span>
                        </a>
                        <a class="price">
                            <img class="coin" src="{% static 'img/coin.png' %}">
                            <span class="description">Adicionar preço</span>
                        </a>
                        <div class="tags">
                            <img class="tag" src="{% static 'img/tag-black-shape.png' %}">
                            <div class="group-tags">
                                {% for tag in tags %}
                                <div class="row-tag">
                                    <div class="tag-box">{{tag.name}}</div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="update-buttons">
                        <div class="encapsulate-call">
                            <button><i class="icon-call-2"></i></button>
                        </div>
                        <div class="encapsulate-pay">
                            <button><i class="icon-pay-2"></i></button>
                        </div>
                        <div class="encapsulate-email">
                            <button><i class="icon-email-2"></i></button>
                        </div>
                    </div>
                    </div>
                    <div class="notes">
                        <span class="description">Anotações:</span>
                        <form class="new-note"method = "POST" autocomplete="off">
                            {% csrf_token %}
                            {% if form.errors %}
                                <div class="alert alert-error">
                                <p>Por favor, corrija os seguintes erros antes de salvar novamente: </p>
                                <ul>
                                    {% for field in form %}
                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                                </div>
                            {% endif %}
                            
                                {% render_field form.notes class="form-control notes-popup" %}
                            <button type="submit" class="button-note"><a class="test">Salvar</a></button>
                        </form>
                        <!-- <form method="POST" autocomplete="off"></form>
                            {% csrf_token %}

                            {% if form.errors %}
                                <div class="alert alert-error">
                                <p>Por favor, corrija os seguintes erros antes de salvar novamente: </p>
                                <ul>
                                    {% for field in form %}
                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                                </div>
                            {% endif %}
                            {% render_field form.notes class+="notes-popup" %}
                            <button class="button-note" type="submit">Salvar</button>
                        </form> -->
                    </div>
                </div>
            </div>
            <!-- <h1 class="new-call-title">POPUP</h1>
            <a>llllll</a> -->
            
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        let params = new URLSearchParams(document.location.search.substring(1))
        let pk = params.get("pk")
        $('.date').attr("href", `/activities/call_scheduling/?pk=${pk}`);
        $('.price').attr("href", `/activities/change_price/?pk=${pk}`);
        // $('.test').attr("href", `/activities/call_popup/?pk=${pk}`);
    </script>
{% endblock %}

activities/templates/call-scheduling.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block links %}
<link rel="stylesheet" type="text/css" href = "{% static 'css/call-scheduling.css' %}">
<link rel="stylesheet" type="text/css" href="../../static/datetimepicker-2.5.20/jquery.datetimepicker.css"/ >
{% endblock %}

{% block content %}
        
    <div class = "popup">
        <form class="new-date" method = "POST" autocomplete="off">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-error">
                <p>Por favor, corrija os seguintes erros antes de salvar novamente: </p>
                <ul>
                    {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </ul>
                </div>
            {% endif %}
            <h1 class="new-date-title">Agendar Chamada</h1>
    
            <!-- Name -->
            <div class="new-date-input">
                <label for="new-date-name">
                    <span class="new-date-number">1</span> Data e hora da chamada
                </label>
                {% render_field form.date_scheduling class="form-control" %}
            </div>
            <button type="submit" class="new-date-submit">Agendar</button>
        </form>
    </div>
        
{% endblock %}

{% block scripts %}
<script src="../../static/datetimepicker-2.5.20/jquery.js"></script>
<script src="../../static/datetimepicker-2.5.20/build/jquery.datetimepicker.full.min.js"></script>
<script src="../../static/js/main.js"></script>
<script>
        jQuery.datetimepicker.setLocale('pt-BR');
        jQuery('#id_date_scheduling').datetimepicker({
            i18n:{
            de:{
            months:[
            'Janeiro','Fevereiro','Março','Abril',
            'Maio','Junho','Julho','Agosto',
            'Setembro','Outubro','Novembro','Dezembro',
            ],
            dayOfWeek:[
            "So.", "Mo", "Di", "Mi", 
            "Do", "Fr", "Sa.",
            ]
            }
            },
            format:'d/m/Y H:i',
        });
</script>

{% endblock %}

    

activities/templates/change-price.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block links %}
<link rel="stylesheet" type="text/css" href = "{% static 'css/change-price.css' %}">
{% endblock %}

{% block content %}
        
    <div class = "popup">
        <form class="new-price" method = "POST" autocomplete="off">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-error">
                <p>Por favor, corrija os seguintes erros antes de salvar novamente: </p>
                <ul>
                    {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </ul>
                </div>
            {% endif %}
            <h1 class="new-price-title">Modificar Valor</h1>
    
            <!-- Name -->
            <div class="new-price-input">
                <label for="new-price-name">
                    <span class="new-price-number">1</span> Valor
                </label>
                {% render_field form.value class="form-control" %}
            </div>
            <button type="submit" class="new-price-submit">Modificar</button>
        </form>
    </div>
        
{% endblock %}

{% block scripts %}
{% endblock %}

    

activities/templates/system-metrics.html
{% extends 'app.html' %}
{% load static %}
{% load widget_tweaks %}

{% block links %}
{% endblock %}

{% block app_content %}

  {% include "includes/total-calls-charts.html" %}
{% endblock %}

{% block scripts %}
{% endblock %}