calls/urls.py
from django.urls import path
from .views import CallModalView

app_name='calls'

urlpatterns = [
    path('modal/', CallModalView.as_view(), name="modal"),
]

users/urls.py
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    ProfileView,
    SignupView,
    CollaboratorProfileView,
    CollaboratorListView,
)

from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password-reset/', PasswordResetView.as_view(
            template_name='users/password-reset.html',
            success_url=reverse_lazy('users:password-reset-done'),
            email_template_name='users/password-reset-email.html',
            html_email_template_name='users/email-clickcall.html',
            subject_template_name='users/password-reset-subject.txt',
            from_email='Suporte Clickcall <templatedmailtest@gmail.com>'
        ),
        name='password-reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(
            template_name='users/password-reset-done.html'
        ),
        name='password-reset-done'),

    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(
            template_name='users/password-reset-confirm.html',
            success_url=reverse_lazy('users:password-reset-complete'),
        ),
        name="password-reset-confirm"),

    path('reset/done/', PasswordResetCompleteView.as_view(
            template_name='users/password-reset-complete.html'
        ),
        name="password-reset-complete"),

    path('collaborator-profile/', CollaboratorProfileView.as_view(),
        name='collaborator-profile'),

    path('collaborator-list/', CollaboratorListView.as_view(), 
        name='collaborator-list'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .manager import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom model to users of clickcall
    """

    created = models.DateTimeField(auto_now_add=True,)
    updated = models.DateTimeField(auto_now=True)

    email = models.EmailField(unique=True)

    name = models.CharField(max_length=256,
                            verbose_name="Login")
    avatar = models.ImageField(
            blank=True,
            upload_to='users/avatars/',
            default='users/avatars/default.png')

    function = models.CharField(max_length=50, default='Colaborador',
                                verbose_name="Função")
    phone = models.CharField(max_length=15, verbose_name="Telefone")

    ramal = models.CharField(max_length=15, verbose_name="Ramal")

    sector = models.CharField(max_length=50, verbose_name="Área")

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    COLABORATOR = 'CO'
    SUPERVISOR = 'SU'

    FUNCTION_CHOICES = (
        (COLABORATOR, 'Colaborador'),
        (SUPERVISOR, 'Supervisor'),
    )

    function = models.CharField(
        max_length=2,
        choices=FUNCTION_CHOICES,
        default=COLABORATOR,
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"

    def __str__(self):
        return self.email + "("+self.phone+" r "+self.ramal+")"

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from .models import User


class SignupForm(forms.ModelForm):
    """
    Form to handle the signup process
    """
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = [
            'name',
            'email',
            'avatar',
            'function',
            'phone',
            'ramal',
            'sector',
            ]

    def clean(self):
        cleaned_data = super(SignupForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                'Erro: as senhas não são iguais'
            )
        return cleaned_data

    def save(self, commit=True):
        raw_password = self.cleaned_data.get('password')
        self.instance.username = self.cleaned_data.get('username')
        self.instance.set_password(raw_password)
        if commit:
            self.instance.save()
        return self.instance

users/views.py
from django.views import generic
from django.contrib.auth import views as auth_views
from django.contrib.auth import get_user_model
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import redirect

from .models import User
from .forms import SignupForm
from django.views.generic import TemplateView



class SignupView(generic.FormView):
    form_class = SignupForm
    success_url = 'users:login'
    template_name = 'users/signup.html'
    redirect_authenticated_user = True

    model = get_user_model()

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy(self.success_url))
        return super(SignupView, self).get(request)

    def form_valid(self, form):
        self.object = form.save()
        return redirect('users:login')


class LogoutView(auth_views.LogoutView):
    next_page = 'users:login'


class LoginView(auth_views.LoginView):
    """
    View that handles the login process
    """
    success_url = reverse_lazy('users:profile')
    template_name = 'users/login.html'
    redirect_authenticated_user = True
    redirect_field_name = success_url


class ProfileView(generic.TemplateView):
    template_name = 'users/profile.html'
    model = User

class CollaboratorProfileView(TemplateView):
    template_name = 'users/collaborator-profile.html'
    model = User

class CollaboratorListView(generic.TemplateView):
    template_name = 'users/collaborator-list.html'

users/templates/users/collaborator-list.html
{% load staticfiles%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Click Call - Collaborator List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/collaborator-list.css'%}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/fontello.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700" rel="stylesheet">
    <script src="main.js"></script>
</head>
<body>
    <div class="container">
        <div class="title-and-button">
            <div class="title">Lista de Colaboradores</div>
                <a><button type="button" class="add-goal"><i class="icon-plus-button"></i>Atribuir metas</button></a>
        </div>
        <table class="collaborator-table">
            <tr>
                <th>Nome do colaborador</th>
                <th>Número</th>
                <th>Último acesso</th>
                <th>Email</th>
            </tr>
            <tr>
                <td>Nome do colaborador</td>
                <td>(81) X XXXX-XXXX</td>
                <td>21/09/2018 - 20:30h</td>
                <td>contato@exemplo.com</td>
            </tr>
            <tr>
                <td>Nome do colaborador</td>
                <td>(81) X XXXX-XXXX</td>
                <td>21/09/2018 - 20:30h</td>
                <td>contato@exemplo.com</td>
            </tr>
            <tr>
                <td>Nome do colaborador</td>
                <td>(81) X XXXX-XXXX</td>
                <td>21/09/2018 - 20:30h</td>
                <td>contato@exemplo.com</td>
            </tr>
            <tr>
                <td>Nome do colaborador</td>
                <td>(81) X XXXX-XXXX</td>
                <td>21/09/2018 - 20:30h</td>
                <td>contato@exemplo.com</td>
            </tr>
            <tr>
                <td>Nome do colaborador</td>
                <td>(81) X XXXX-XXXX</td>
                <td>21/09/2018 - 20:30h</td>
                <td>contato@exemplo.com</td>
            </tr>
            <tr>
                <td>Nome do colaborador</td>
                <td>(81) X XXXX-XXXX</td>
                <td>21/09/2018 - 20:30h</td>
                <td>contato@exemplo.com</td>
            </tr>
            <tr>
                <td>Nome do colaborador</td>
                <td>(81) X XXXX-XXXX</td>
                <td>21/09/2018 - 20:30h</td>
                <td>contato@exemplo.com</td>
            </tr>

        </table>
    </div>
    
</body>
</html>

users/templates/users/collaborator-profile.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Click Call - Collaborator Profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen" href="{%static 'css/collaborator-profile.css'%}">
    <link rel="stylesheet" type="text/css" media="screen" href="{%static 'css/fontello.css'%}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
    <script async src="//jsfiddle.net/ab2gy/embed/"></script>
    <script src="../../static/js/change-frame.js"></script>
</head>
<body>
    <div class="background">
        <div class="container">
            <div class="personal-informations">
                <div class="avatar-and-goals">
                    <img src="../../static/img/user.png" class="avatar">
                    <button class="add-goals" type="button"><i class="icon-plus-button" ></i>Atribuir metas</button>
                </div>
                <div class="personal-informations-text">
                    <div class="full-name">
                        <span class="title-name">Nome Completo</span>
                        <span class="name">José Augusto da Silva</span>
                    </div>
                    <div class="double">
                        <div class="email-and-phone">
                            <div class="email">
                                <span class="title">Email</span>
                                <span class="subtitle">joseaugusto20@exemplo.com</span>
                            </div>
                            <div class="ramal">
                                <span class="title">Ramal</span>
                                <span class="subtitle">XXX</span>
                            </div>
                            <div class="phone">
                                <span class="title">Telefone</span>
                                <span class="subtitle">(81) X XXXX-XXX</span>
                            </div>
                        </div>
                        <div class="text">
                            <div class="function-and-sector">
                                <div class="function">
                                    <span class="title">Função</span>
                                    <span class="subtitle">Colaborador</span>
                                </div>
                                <div class="sector">
                                    <span class="title">Setor</span>
                                    <span class="subtitle">Nome do setor</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="history-performance">
                <div class="history">
                    <span class="history-title">Histórico de Metas</span>
                    <div class="history-content">
                        <span class="day">Hoje/<span class="date"> Ter 13 Ago</span></span>
                        <div class="scroll">
                            <span class="pendent-goals" id="pk-1" onclick="cross('pk','1')">Prospectar 15 novos clientes</span>
                            <span class="pendent-goals" id="pk-2" onclick="cross('pk','2')">Atualizar lista X</span>
                            <span class="pendent-goals" id="pk-1" onclick="cross('pk','1')">Prospectar 15 novos clientes</span>
                            <span class="pendent-goals" id="pk-2" onclick="cross('pk','2')">Atualizar lista X</span>
                            <span class="pendent-goals" id="pk-1" onclick="cross('pk','1')">Prospectar 15 novos clientes</span>
                            <span class="pendent-goals" id="pk-2" onclick="cross('pk','2')">Atualizar lista X</span>
                            <span class="pendent-goals" id="pk-1" onclick="cross('pk','1')">Prospectar 15 novos clientes</span>
                            <span class="pendent-goals" id="pk-2" onclick="cross('pk','2')">Atualizar lista X</span>
                            <span class="pendent-goals" id="pk-1" onclick="cross('pk','1')">Prospectar 15 novos clientes</span>
                            <span class="pendent-goals" id="pk-2" onclick="cross('pk','2')">Atualizar lista X</span>
                            <span class="pendent-goals" id="pk-1" onclick="cross('pk','1')">Prospectar 15 novos clientes</span>
                            <span class="pendent-goals" id="pk-2" onclick="cross('pk','2')">Atualizar lista X</span>
                            <span class="pendent-goals" id="pk-1" onclick="cross('pk','1')">Prospectar 15 novos clientes</span>
                            <span class="pendent-goals" id="pk-2" onclick="cross('pk','2')">Atualizar lista X</span>
                            <span class="pendent-goals" id="pk-1" onclick="cross('pk','1')">Prospectar 15 novos clientes</span>
                            <span class="pendent-goals" id="pk-2" onclick="cross('pk','2')">Atualizar lista X</span>
                            <span class="pendent-goals" id="pk-1" onclick="cross('pk','1')">Prospectar 15 novos clientes</span>
                            <span class="pendent-goals" id="pk-2" onclick="cross('pk','2')">Atualizar lista X</span>
                            <span class="pendent-goals" id="pk-1" onclick="cross('pk','1')">Prospectar 15 novos clientes</span>
                            <span class="pendent-goals" id="pk-2" onclick="cross('pk','2')">Atualizar lista X</span>
                            <span class="pendent-goals" id="pk-1" onclick="cross('pk','1')">Prospectar 15 novos clientes</span>
                            <span class="pendent-goals" id="pk-2" onclick="cross('pk','2')">Atualizar lista X</span>
                        </div>
                    </div>
                </div>
                <div class="performance">
                        <div class="performance-and-period">
                            <span class="performance-title">Desempenho</span>
                            <a href="https://www.w3schools.com" target="iframe_a" id="year-1" onclick="frame('year','1')" class="performance-subtitle-blue">Anual</a>
                            <a id="month-2" onclick="frame('month','2')" class="performance-subtitle">Mensal</a>
                            <a id="week-3" onclick="frame('week','3')" class="performance-subtitle">Semanal</a>
                            <a id="day-4" onclick="frame('day','4')" class="performance-subtitle">Diário</a>
                        </div>
                        <div class="frame">
                            <iframe name="iframe_a" src="/collaborator-profile/login.html"></iframe>
                        </div>
                    </div>
            </div>
            <div class="completed-goals">
                <span class="completed-goals-title">Metas Concluídas</span>
                <div class="goals-boxes-container">
                    <div class="goals-boxes">
                        <span class="goals-day">Hoje</span>
                        <span class="amount">6/10</span>
                        <span class="goals-finished">concluídas</span>
                    </div>
                    <div class="goals-boxes">
                            <span class="goals-day">Hoje</span>
                            <span class="amount">6/10</span>
                            <span class="goals-finished">concluídas</span>
                    </div>
                    <div class="goals-boxes">
                            <span class="goals-day">Hoje</span>
                            <span class="amount">6/10</span>
                            <span class="goals-finished">concluídas</span>
                    </div>
                    <div class="goals-boxes">
                            <span class="goals-day">Hoje</span>
                            <span class="amount">6/10</span>
                            <span class="goals-finished">concluídas</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
Entrar
{% endblock title %}

{% block links %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/login.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,700" rel="stylesheet">
{% endblock links %}

{% block content %}
<div class="full-screen">
  <div class="container">
    <img class="logo" src="{% static 'img/logo1.png' %}">
     
    <form method="post" class="container">
      {% csrf_token %}
      <div class="form-container">
        {% render_field form.username placeholder="exemplo@clickcall.com.br" %}
        {% render_field form.username.errors %}

        <div class="password">
          {% render_field form.password id="pwd" placeholder="Senha" %}
          {% render_field form.password.errors %}
          <button type="button" onclick="showPassword()">
            <img id="eye" class="show" src={% static 'img/eyes-closed.png' %}>
          </button>
        </div>
      </div>
        {{ form.non_field_errors }}
    <button class="login-button" type="submit">Login</button>
    </form>
    <a href={% url 'users:password-reset' %} 
        class="login-link forget-password transition">Esqueceu sua senha?</a>
    <a href={% url 'users:signup' %} 
        class="login-link register transition">Cadastre-se</a>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/show-password.js' %}"></script>
{% endblock scripts %}

users/templates/users/password-reset-complete.html
{% extends "base.html" %}

{% block title %}
Reset Complete
{% endblock title %}

{% block content %}
Successfully changed password!
<ul>
    <li><a href={% url 'users:login' %}>Login</a></li>
</ul>
{% endblock content %}

users/templates/users/password-reset-confirm.html
{% extends "base.html" %}

{% block title %}
Reset confirm
{% endblock title %}

{% block content %}
    <form method="POST">
        {% csrf_token %} 
        {{form.as_p}}
        <input type="submit" value="Enviar" />
    </form>
{% endblock content %}

users/templates/users/password-reset-done.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Redefinição de Senha 
{% endblock title %}
{% block links %}
<link rel="stylesheet" href={% static 'css/password-reset-done.css' %} type="text/css" media="all">    
{% endblock links %}

{% block content %}
<div class="full-screen">
    <div class="container">
        <img class="logo" src="{% static 'img/logo1.png' %}">
        <span class="verification">Verifique seu email!</span>
        <span class="instructions">Enviamos instruções para <span>exemplo@clickcall.org.br</span></span>
        <span class="resend">Caso não tenha recebido, verifique sua lixeira ou solicite reenvio do email.</span>

        <a href={% url 'users:password-reset' %}>
            <button class="resend-button" type="submit">Reenviar email</button>
        </a>

        <a href={% url 'users:password-reset' %}>
            <button class="back-button" type="button">
                <img src={% static 'img/left-arrow.png' %}>
            </button>
        </a>

    </div>
</div>    
{% endblock content %}

users/templates/users/password-reset-email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'users:password-reset-confirm' uidb64=uid token=token %}

users/templates/users/password-reset.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block links %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/password-reset.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,700" rel="stylesheet">
{% endblock links %}

{% block title %}
Redefinir senha
{% endblock title %}

{% block content %}
<div class="full-screen">
  <form method="POST" class="container">
    {% csrf_token %}
    <img class="logo" src={% static 'img/logo1.png'%}>
    <span>Enviaremos um email com as informações para redefinição de senha</span>
    <div class="input-back">
      <a href={% url 'users:login' %}>
        <button type="button"><img src={% static 'img/left-arrow.png'%}>
        </button>
      </a>
      {% render_field form.email placeholder="email" %}
    </div>
    <button type="submit">Redefinir senha </button>
  </form>
</div>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

users/templates/users/profile.html
{% extends "app.html" %}
{% load static %}

{% block title %}
Meu Perfil
{% endblock %}

{% block links %}
<link rel="stylesheet" href={% static 'css/profile.css' %} type="text/css" media="all"> 
{% endblock %}

{% block app_content %}
<h1 class="app-title">Meu Perfil</h1>
<div class="profile-container">
  <div class="profile-infos">
    <div class="profile-info-block">
      <h1 class="profile-info-label">Nome Completo</h1>
      <h2 class="profile-info">{{ user.name }}</h2>
    </div>

    <div class="profile-info-block">
      <h1 class="profile-info-label">Email</h1>
      <h2 class="profile-info">{{ user.email }}</h2>
    </div>

    <div class="profile-info-block">
      <h1 class="profile-info-label">Função</h1>
      <h2 class="profile-info">{{ user.get_function_display }}</h2>
    </div>

    <div class="profile-info-block">
      <h1 class="profile-info-label">Ramal</h1>
      <h2 class="profile-info" >{{ user.ramal }}</h2>
    </div>

    <div class="profile-info-block">
      <h1 class="profile-info-label">Telefone</h1>
      <h2 class="profile-info">{{ user.phone }}</h2>
    </div>

    <div class="profile-info-block">
      <h1 class="profile-info-label">Setor</h1>
      <h2 class="profile-info">{{ user.sector }}</h2>
    </div>
  </div>
  <div class="profile-image">
    <!-- <img src={{user.avatar.url}} alt="User Image"> -->
  </div>
</div>

{% endblock %}

users/templates/users/signup.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
Cadastrar conta
{% endblock %}

{% block links %}
<link rel="stylesheet" href={% static 'css/logon.css' %}>
{% endblock %}

{% block content %}
<div class="all">
  <div>
    <img class="logo" src={% static 'img/logo1.png' %} />
  </div>

  <form method="post" enctype="multipart/form-data" class="form">
    {{ form.non_field_errors }}
    {% csrf_token %}
    <div class="form-fields">
      <div class="side-1">
        <div class="fields-box">
          {{ form.name.errors }}
          {% render_field form.name class="field" placeholder="Nome"%}
        </div>

        <div class="fields-box">
          {{ form.phone.errors }}
          {% render_field form.phone class="field" placeholder="Telefone"%}
        </div>

        <div class="fields-box">
          {{ form.ramal.errors }}
          {% render_field form.ramal class="field" placeholder="Ramal"%}
        </div>

        <div class="fields-box">
          {{ form.function.errors }}
          {% render_field form.function class="field" placeholder="Função"%}
        </div>

        <div class="fields-box">
          {{ form.sector.errors }}
          {% render_field form.sector class="field" placeholder="Setor"%}
        </div>
      </div>

      <div id="divisor-line"></div>

      <div>
        <div class="side-2">
          <!-- {{ form.avatar }} -->
          <label for="upload-image" id="image">
            <img src={% static 'img/user.png' %} alt="">
          </label>
              {% render_field form.avatar id="upload-image" %}
        </div>

        <div class="fields-box">
          {{ form.email.errors }}
          {% render_field form.email class="field" placeholder="E-mail"%}
        </div>

        <div class="fields-box">
          {{ form.password.errors }}
          {% render_field form.password class="field" placeholder="Senha"%}
        </div>

        <div class="fields-box">
          {% render_field form.confirm_password class="field" id="last-field" placeholder="Confirme sua senha"%}
        </div>
      </div>
    </div>
    <button type="submit" id="logon-button">Cadastre-se</button>
  </form>
</div>
{% endblock %}